trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

# build docker image
stages:
  - stage:
    displayName: 'build docker image'
    jobs:
      - job: 
        displayName: 'build docker image and publish k8s manifests'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'build and push docker image'
            inputs:
              containerRegistry: 'DockerHub-connection'
              repository: 'pavelsergeev/currency-exchange-devops'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: '$(System.DefaultWorkingDirectory)'
              tags: '$(tag)'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/configuration/kubernetes'
              Contents: '**/*.yaml'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'publish k8s manifests'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'manifests'
              publishLocation: 'Container'

  - stage: 
    displayName: 'publish'
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'download k8s manifest'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'manifests'
            itemPattern: '**/*.yaml'
            targetPath: '$(System.ArtifactsDirectory)'
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'kubernetes-service-connection'
            namespace: 'default'
            manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
            containers: 'pavelsergeev/currency-exchange-devops:$(tag)'